name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  dump_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_HEAD_CONTEXT: ${{ toJson(github.event.head) }}
        run: echo "$GITHUB_HEAD_CONTEXT"