name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  dump_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Pull Request body context
        env:
          GITHUB_PR_BODY_CONTEXT: ${{ toJson(github.event.pull_request.body) }}
        run: echo "$GITHUB_PR_BODY_CONTEXT"